---

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Print service facts
  ansible.builtin.debug:
    var: ansible_facts.services
    verbosity: 1

- name: Create list of known services
  ansible.builtin.set_fact:
    known_services: "{{ ansible_facts.services | map('extract', ansible_facts.services, 'name') | list }}"

- name: Show known services
  ansible.builtin.debug:
    var: known_services
    verbosity: 1
