known_output_plugins:
  - pvr350
  - softhdcuvid
  - softhddevice
  - softhddrm
  - softhdvaapi
  - vaapidevice
  - xine
  - xineliboutput

# The following variables are intentionally not defined here:

# must be one of the above values if the default doesn't fit
# selected_frontend = softhddevice

# name of the VDR output plugin deb-package to install,
# overwrite if you want something else than the default
# it must be one of:
#  - vdr-plugin-softhddevice
#  - vdr-plugin-softhddevice-cuvid
#  - vdr-plugin-softhddevice-openglosd
#  - vdr-plugin-softhdcuvid
#  - vdr-plugin-softhddrm
#  - vdr-plugin-softhdvaapi
#  - vdr-plugin-vaapidevice
#  - vdr-plugin-xine
#  - vdr-plugin-xineliboutput
#
# vdr_output_plugin = vdr-plugin-softhddevice
