---
# file roles/autoinstall-atric-usb/tasks/main.yml

- name: Install and configure Atric IR-WakeupUSB
  when: '"10c4:876c" in usb'
  block:
    - name: Apt | install lirc-drv-yausbir
      ansible.builtin.apt:
        name: lirc-drv-yausbir
        state: present
      tags:
        - packages

    - name: Write lirc configuration
      ansible.builtin.template:
        src: templates/lirc_options.conf.j2
        dest: /etc/lirc/lirc_options.conf
        mode: '0644'
      tags:
        - config
        - systemd

    - name: Enable lircd, eventlircd, lircd2uinput
      ansible.builtin.systemd:
        name: '{{ item }}'
        enabled: true
        state: started
        masked: false
        daemon_reload: true
      loop:
        - eventlircd.service
        - lircd2uinput.service
        - lircd.service
      tags:
        - systemd
