---
# file roles/autoinstall-pvr350/tasks/main.yml

- name: Apt | install vdr-plugin-pvr350 if connected
  ansible.builtin.apt:
    name: vdr-plugin-pvr350
  when: '"0070:4000" in ansible_facts["pci"]'
  notify: ["Restart VDR"]
