- name: Apt | install vdr-addon-lifeguard-ng
  ansible.builtin.apt:
    name: vdr-addon-lifeguard-ng
    state: present

- name: Expand template for vdr-addon-lifeguard-ng configuration file
  ansible.builtin.template:
    src: templates/lifeguard.conf.j2
    dest: /etc/lifeguard.conf
    mode: '0644'
  notify: Restart vdr-addon-lifeguard-ng
