---
# file: roles/samba-install/tasks/main.yml

- name: Install samba server
  ansible.builtin.apt:
    name:
      - samba
      - samba-common
      - samba-common-bin
      - samba-vfs-modules
      - smbclient
      - tdb-tools
    state: present
    install_recommends: false
