---
# file roles/autoinstall-hauppauge-pvr/tasks/main.yml

- name: Apt | install vdr-plugin-pvrinput if a haupauge pvr card is found
  ansible.builtin.apt:
    name: vdr-plugin-pvrinput
  when: '"0070:4000" in ansible_facts["pci"] or "4444:0016" in ansible_facts["pci"]'
  notify: ["Restart VDR"]
