---

- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Add configuration for nginx
  ansible.builtin.template:
    src: templates/nginx.j2
    dest: /etc/nginx/sites-available/defaut