kodi_as_flatpak: true
kodi_use_gbm: false
kodi_tty: 8
kodi_config_dir: '{{ vdr.home }}/{{ ".var/app/tv.kodi.Kodi/data" if kodi_as_flatpak else ".kodi" }}'
kodi_allowed_dirs_flatpak:
  - home
  - /media
  - /net
  - /srv/audio
  - /srv/files
  - /srv/picture
  - /srv/video
  - /home/vdr/Downloads
  - /var/lib/vdr/Downloads

kodi_restricted_dirs_flatpak: []
