---
# file: displays.yml
# this playbook runs the yavdr-xorg role

- name: Rescan displays
  hosts: all
  become: true

  roles:
    - yavdr-xorg
    - grub-config
  # tasks:
  #   - name: show preferred refreshrate
  #     ansible.builtin.debug:
  #       var: "{{ item }}"
  #     loop:
  #       - preferred_outputs
  #       - preferred_resolutions
  #       - preferred_refreshrates

  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: handlers/main.yml
