- name: Get information about usb and pci hardware and loaded kernel modules
  hardware_facts:
    usb: true
    pci: true
    serial: true
    modules: true
    gpus: true
    acpi_power_modes: true
  tags:
    - always

- name: Show collected hardware facts
  ansible.builtin.debug:
    msg: "{{ item }}"
    verbosity: 0
  loop:
    - "{{ usb }}"
    - "{{ pci }}"
    - "{{ serial_ports }}"
    - "{{ gpus }}"
    - "{{ modules }}"
    - "{{ acpi_power_modes }}"
    - "{{ nvidia_detected }}"
    - "{{ intel_detected }}"
    - "{{ amd_detected }}"
    - "{{ virtualbox_detected }}"

- name: Get detailed PCI device information
  pci_facts:
  tags:
    - always

- name: Show PCI devices
  ansible.builtin.debug:
    var: pci_devices
    verbosity: 1

- name: Set known vdr output plugins
  ansible.builtin.set_fact:
    vdr_output_plugins:
      - softhddevice
      - xineliboutput
      - xine
