---

- name: 'Stop services for Xorg'
  ansible.builtin.systemd:
    name: '{{ item.instance_name }}'
    state: stopped
  notify: 'Stop {{ item.service_name | replace(".service", "", 1) | default(omit) }}' # TODO: check if this works as intended
  loop: '{{ xorg_services }}'
  when: item.instance_name in known_services | default([])
