---
# file: roles/vdr/tasks/main.yml

- name: Apt | install basic vdr packages
  ansible.builtin.apt:
    name:
      - vdr
      - vdrctl
      - vdr-plugin-dbus2vdr
    state: present
    install_recommends: false
- name: Add svdrp and svdrp-disc to /etc/services
  ansible.builtin.lineinfile:
    dest: /etc/services
    state: present
    line: "{{ item }}"
  loop:
    - "svdrp            6419/tcp"
    - "svdrp-disc       6419/udp"

- name: Configure dbus2vdr for vdr instance id "{{ vdr.instance_id | default(0) }}" and user "{{ vdr.user }}"
  vars:
    vdr_instance_id: "{{ '' if vdr.instance_id | default(0) | int == 0 else vdr.instance_id }}"
  ansible.builtin.template:
    src: dbus2vdr/de.tvdr.vdr.conf.j2
    dest: /etc/dbus-1/system.d/de.tvdr.vdr.conf
    mode: "0644"

- name: Create vdr recdir
  ansible.builtin.file:
    state: directory
    owner: "{{ vdr.user }}"
    group: "{{ vdr.group }}"
    dest: "{{ vdr.recdir }}"
    mode: "0775"

- name: Set vdr charset override
  ansible.builtin.template:
    src: conf.d/02-vdr-charset-override.conf.j2
    dest: /etc/vdr/conf.d/02-vdr-charset-override.conf
    mode: "0644"

- name: Set option to use hide-first-recording-level patch
  ansible.builtin.template:
    src: conf.d/04-vdr-hide-first-recordinglevel.conf.j2
    dest: /etc/vdr/conf.d/04-vdr-hide-first-recordinglevel.conf
    mode: "0644"

- name: Set instance id for vdr
  ansible.builtin.template:
    src: conf.d/05-vdr-instance.conf.j2
    dest: /etc/vdr/conf.d/05-vdr-instance.conf
    mode: "0644"

- name: Set option to define recordings directory
  ansible.builtin.template:
    src: conf.d/06-vdr-recordings.conf.j2
    dest: /etc/vdr/conf.d/06-vdr-recordings.conf
    mode: "0644"

- name: Bind VDR to tty9
  ansible.builtin.template:
    src: conf.d/07-vdr-tty.conf.j2
    dest: /etc/vdr/conf.d/07-vdr-tty.conf
    mode: "0644"

- name: Create local dir in recdir
  ansible.builtin.file:
    state: directory
    owner: "{{ vdr.user }}"
    group: "{{ vdr.group }}"
    mode: "0775"
    dest: "{{ vdr.recdir }}/local"
  when: vdr.hide_first_recording_level

- name: Set VDR_ID for shells in /etc/profile.d/
  ansible.builtin.template:
    src: vdr-dbus-send-vdr-id.sh
    dest: /etc/profile.d/vdr-dbus-send-vdr-id.sh
    mode: "0755"
  notify: ["Reboot required"]

# TODO: set user etc. in /etc/vdr/conf.d/
- name: Apt | install additional vdr plugins
  ansible.builtin.apt:
    name: "{{ vdr_plugins }}"
    state: present
    install_recommends: false
  notify: ["Restart VDR"]

- name: Ensure vdr is stopped
  ansible.builtin.systemd:
    name: vdr.service
    state: stopped
  notify: ["Start VDR"]

- name: "VDR configuration | copy remote.conf if it doesn't exist yet"
  ansible.builtin.copy:
    src: remote.conf
    dest: "{{ vdr.confdir }}/remote.conf"
    owner: "{{ vdr.user }}"
    group: "{{ vdr.group }}"
    mode: "0644"
    force: false

- name: "VDR configuration | create keymacros.conf"
  ansible.builtin.template:
    src: keymacros.conf.j2
    dest: "{{ vdr.etc_confdir }}/keymacros.conf"
    owner: "{{ vdr.user }}"
    group: "{{ vdr.group }}"
    mode: "0644"
    force: true

- name: "VDR configuration | create scr.conf"
  ansible.builtin.template:
    src: scr.conf.j2
    dest: "{{ vdr.etc_confdir }}/scr.conf"
    owner: "{{ vdr.user }}"
    group: "{{ vdr.group }}"
    mode: "0644"
    force: true

- name: "VDR configuration | create diseqc.conf"
  ansible.builtin.template:
    src: diseqc.conf.j2
    dest: "{{ vdr.etc_confdir }}/diseqc.conf"
    owner: "{{ vdr.user }}"
    group: "{{ vdr.group }}"
    mode: "0644"
    force: true

- name: "VDR configuration | download channels.conf if it doesn't exist yet"
  ansible.builtin.get_url:
    url: "{{ vdr_channels_conf }}"
    dest: "{{ vdr.confdir }}/channels.conf"
    owner: "{{ vdr.user }}"
    group: "{{ vdr.group }}"
    mode: "0644"
    force: false
  when: vdr_channels_conf is defined

- name: Touch the channels.conf
  ansible.builtin.file:
    path: "{{ vdr.confdir }}/channels.conf"
    state: touch
    mode: "0744"

- name: "VDR configuration | svdrphosts.conf"
  ansible.builtin.template:
    src: templates/svdrphosts.conf.j2
    dest: "{{ vdr.etc_confdir }}/svdrphosts.conf"
    mode: "0644"
  vars:
    svdrphosts: "{{ vdr_svdrphosts | default(vdr_allowed_hosts) }}"

- name: "VDR configuration | /etc/default/vdr"
  ansible.builtin.template:
    src: templates/default_vdr.j2
    dest: /etc/default/vdr
    mode: "0644"

- name: Ensure directory '/etc/vdr/xineliboutput' exists
  ansible.builtin.file:
    state: directory
    mode: "0775"
    dest: "/etc/vdr/plugins/xineliboutput"

- name: "VDR configuration | allowed_hosts.conf for xineliboutput"
  ansible.builtin.template:
    src: templates/generic_allowed_hosts.conf.j2
    dest: "/etc/vdr/plugins/{{ vdr_service }}/allowed_hosts.conf"
    mode: "0644"
  vars:
    allowed_hosts: "{{ xineliboutput_allowed_hosts | default(vdr_allowed_hosts) }}"
    vdr_service: xineliboutput

- name: "VDR configuration | xineliboutput.conf host settings"
  ansible.builtin.template:
    src: templates/xineliboutput.conf.j2
    dest: /etc/vdr/conf.avail/xineliboutput.conf
    mode: "0644"
  vars:
    allowed_hosts: "{{ xineliboutput_allowed_hosts | default(vdr_allowed_hosts) }}"

- name: "Disable/enable wait-for-dvb@.service for configured devices"
  ansible.builtin.systemd:
    enabled: '{{ "yes" if item in wait_for_dvb_devices | default([]) else "no" }}'
    name: "wait-for-dvb@{{ item }}.service"
  loop: "{{ range(max_num_dvb_devices | default(16)) | list }}"

- name: Ensure directory '/etc/vdr/plugins/vnsiserver' exists
  ansible.builtin.file:
    state: directory
    dest: "/etc/vdr/plugins/vnsiserver"
    mode: "0775"

- name: "VDR configuration | allowed_hosts.conf for vnsiserver"
  ansible.builtin.template:
    src: templates/generic_allowed_hosts.conf.j2
    dest: "/etc/vdr/plugins/{{ vdr_service }}/allowed_hosts.conf"
    mode: "0644"
  vars:
    allowed_hosts: "{{ vnsiserver_allowed_hosts | default(vdr_allowed_hosts) }}"
    vdr_service: vnsiserver

- name: Ensure directory '/etc/vdr/plugins' exists
  ansible.builtin.file:
    state: directory
    mode: "0775"
    dest: "/etc/vdr/plugins/"

- name: "VDR configuration | streamdevhosts.conf for streamdev-server"
  ansible.builtin.template:
    src: templates/generic_allowed_hosts.conf.j2
    dest: "/etc/vdr/plugins/streamdevhosts.conf"
    mode: "0644"
  vars:
    allowed_hosts: "{{ streamdev_server_allowed_hosts | default(vdr_allowed_hosts) }}"
    vdr_service: streamdev-server

- name: Install and configure streamdev-client
  when: streamdev_client_remote_ip | length > 0
  block:
    - name: Apt | install vdr-plugin-streamdev-client
      ansible.builtin.apt:
        state: "present"
        name: "vdr-plugin-streamdev-client"

    - name: Set streamdev-client.RemoteIp
      ansible.builtin.lineinfile:
        state: "present"
        owner: "{{ vdr.user }}"
        group: "{{ vdr.group }}"
        create: true
        path: "{{ vdr.home }}/setup.conf"
        regexp: "^streamdev-client.RemoteIp"
        line: "streamdev-client.RemoteIp = {{ streamdev_client_remote_ip }}"
        mode: "0644"

    - name: Set streamdev-client.RemotePort
      ansible.builtin.lineinfile:
        owner: "{{ vdr.user }}"
        group: "{{ vdr.group }}"
        create: true
        path: "{{ vdr.home }}/setup.conf"
        regexp: "^streamdev-client.RemotePort"
        line: "streamdev-client.RemotePort = {{ streamdev_client_remote_port | default(2004) }}"
        mode: "0644"

    - name: Set streamdev-client.NumProvidedSystems
      ansible.builtin.lineinfile:
        owner: "{{ vdr.user }}"
        group: "{{ vdr.group }}"
        create: true
        path: "{{ vdr.home }}/setup.conf"
        regexp: "^streamdev-client.NumProvidedSystems"
        line: "streamdev-client.NumProvidedSystems = {{ streamdev_client_num_provided_systems | default(1) }}"
        mode: "0644"

    - name: Set streamdev-client.StartClient
      ansible.builtin.lineinfile:
        owner: "{{ vdr.user }}"
        group: "{{ vdr.group }}"
        create: true
        path: "{{ vdr.home }}/setup.conf"
        regexp: "^streamdev-client.StartClient"
        line: "streamdev-client.StartClient = {{ '1' if streamdev_client_remote_ip else '0' }}"
        mode: "0644"

- name: Create directory for vdr.service systemd drop-in files
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "/etc/systemd/system/vdr.service.d/"

- name: Systemd-Drop-In | start vdr.service after network-online.target
  ansible.builtin.template:
    src: templates/systemd/vdr.service.d/network-online.j2
    dest: /etc/systemd/system/vdr.service.d/network-online.conf
    mode: "0644"
  notify: ["Reload Units"]

- name: Systemd-Drop-In | load environment file for vdr.service
  ansible.builtin.template:
    src: templates/systemd/vdr.service.d/vdr-environ.j2
    dest: /etc/systemd/system/vdr.service.d/load-environ.conf
    mode: "0644"
  notify: ["Reload Units"]

- name: Create snippet with yavdr commands
  ansible.builtin.template:
    src: templates/command-hooks/commands.yavdr.conf.j2
    dest: /usr/share/vdr/command-hooks/commands.yavdr.conf
    mode: "0644"

- name: Create helper scripts for reccmds
  ansible.builtin.copy:
    src: reccmds/{{ item }}.sh
    dest: /usr/local/bin/{{ item }}
    mode: "0755"
  loop:
    - removeindex
    - removemarks
    - removeresume
    - vdr-recrepeat

- name: Create snippet for yavdr reccmds to handle marks-, resume- and index-files
  ansible.builtin.template:
    src: reccmds.removemarks.conf.j2
    dest: /usr/share/vdr/command-hooks/reccmds.removemarks.conf
    mode: "0644"

- name: Create snippet for yavdr reccmds to search repeats using epgsearch
  ansible.builtin.template:
    src: reccmds.searchrepeats.conf.j2
    dest: /usr/share/vdr/command-hooks/reccmds.searchrepeats.conf
    mode: "0644"
  when: '"vdr-plugin-epgsearch" in vdr_plugins'
