- name: Update xorg, xrandr and drm variables with values from local facts if needed
  ansible.builtin.set_fact:
    ansible_facts:
      xorg: '{{ ansible_local.xorg.xorg }}'
      xrandr: '{{ ansible_local.xrandr.xrandr }}'
      drm: '{{ ansible_local.drm.drm }}'
  when:
    - ansible_facts.xrandr is undefined
    - ansible_facts.xorg is undefined
    - ansible_facts.drm is undefined

# TODO: expand template for xorg.conf (or snippets)
#       with respect for the available graphics card driver
#       nvidia, noveau, intel, radeon

- name: check for /etc/yavdr/display_config.yml
  ansible.builtin.stat:
    path: /etc/yavdr/display_config.yml
  register: _custom_xorg_config_stat

- name: Load configuration if it exists
  when: _custom_xorg_config_stat.stat.exists and _custom_xorg_config_stat.stat.isreg
  block:
    - name: Slurp /etc/yavdr/display_config.yml
      ansible.builtin.slurp:
        src: /etc/yavdr/display_config.yml
      register: _custom_xorg_config

    - name: Load display configuration
      ansible.builtin.set_fact:
        xorg_config: "{{ _custom_xorg_config.content | b64decode | from_yaml }}"

- name: Set xorg_config from facts if it's undefined
  ansible.builtin.set_fact:
    xorg_config: "{{ xorg_config | default(ansible_facts.XorgConfig) }}"

#- name: Make sure file exists
#  ansible.builtin.file: 
#    path: /etc/yavdr/display_config.yml
#    state: touch
#    mode: "0644"

- name: Show xorg_config facts
  debug:
    var: ansible_facts.XorgConfig
    verbosity: 0


- name: show xorg_config
  debug:
    var: xorg_config
    verbosity: 0

- name: show xrandr config
  debug:
    var: xrandr
    verbosity: 0

- name: Nvidia related config
  when:
    - nvidia_detected | bool
  block:
    - name: Create xorg.conf (for nvidia driver)
      ansible.builtin.template:
        src: templates/xorg.conf.j2
        dest: /etc/X11/xorg.conf
        backup: true
        mode: '0755'

# TODO: this is only useful if VDPAU works with nouveau
# - name: Create nouveau xorg config snippet
#   ansible.builtin.template:
#     src: templates/20-nouveau.conf.j2
#     dest: /etc/X11/xorg.conf.d/20-nouveau.conf
#     mode: '0644'
#   when:
#     - nvidia_detected | bool and not nvidia_driver_installed

- name: Intel xorg config snippet
  ansible.builtin.template:
    src: templates/20-intel.conf.j2
    dest: /etc/X11/xorg.conf.d/20-intel.conf
    mode: '0755'
  when:
    - intel_detected | bool and not nvidia_detected | bool

- name: Amd xorg config snippet
  ansible.builtin.template:
    src: templates/20-amd.conf.j2
    dest: /etc/X11/xorg.conf.d/20-amd.conf
    mode: '0755'
  when:
    - amd_detected | bool and not nvidia_detected | bool
