- name: Update xorg, xrandr and drm variables with values from local facts if needed
  ansible.builtin.set_fact:
    ansible_facts:
      xorg: '{{ ansible_local.xorg.xorg }}'
      xrandr: '{{ ansible_local.xrandr.xrandr }}'
      drm: '{{ ansible_local.drm.drm }}'
  when:
    - ansible_facts.xrandr is undefined
    - ansible_facts.xorg is undefined
    - ansible_facts.drm is undefined

# TODO: expand template for xorg.conf (or snippets)
#       with respect for the available graphics card driver
#       nvidia, noveau, intel, radeon

- name: Load display configuration
  ansible.builtin.include_vars:
    file: /etc/yavdr/display_config.yml
    name: xorg_config


- name: show xorg_config
  debug:
    var: xorg_config
    verbosity: 0

- name: show xrandr config
  debug:
    var: xrandr
    verbosity: 0

- name: Nvidia related config
  when:
    - nvidia_detected | bool
  block:
    - name: Create xorg.conf (for nvidia driver)
      ansible.builtin.template:
        src: templates/xorg.conf.j2
        dest: /etc/X11/xorg.conf
        backup: true
        mode: '0755'

# TODO: this is only useful if VDPAU works with nouveau
# - name: Create nouveau xorg config snippet
#   ansible.builtin.template:
#     src: templates/20-nouveau.conf.j2
#     dest: /etc/X11/xorg.conf.d/20-nouveau.conf
#     mode: '0644'
#   when:
#     - nvidia_detected | bool and not nvidia_driver_installed

- name: Intel xorg config snippet
  ansible.builtin.template:
    src: templates/20-intel.conf.j2
    dest: /etc/X11/xorg.conf.d/20-intel.conf
    mode: '0755'
  when:
    - intel_detected | bool and not nvidia_detected | bool

- name: Amd xorg config snippet
  ansible.builtin.template:
    src: templates/20-amd.conf.j2
    dest: /etc/X11/xorg.conf.d/20-amd.conf
    mode: '0755'
  when:
    - amd_detected | bool and not nvidia_detected | bool
