---
- name: Apt | install vdr-plugin-osd2web
  ansible.builtin.apt:
    name: vdr-plugin-osd2web
    state: present

- name: Expand osd2web.service from template for the session
  ansible.builtin.template:
    src: templates/systemd/user/osd2web.service.j2
    dest: "{{ vdr.home }}/.config/systemd/user/osd2web.service"
    owner: "{{ vdr.user }}"
    group: "{{ vdr.group }}"
    mode: "0644"

- name: Disable websocket-status.service
  ansible.builtin.systemd:
    name: "websocket-status.service"
    daemon_reload: true
    state: stopped
    enabled: false
    masked: false
    scope: user
  become: true
  become_user: "{{ vdr.user }}"
  failed_when: false

- name: Activate and start systemd unit osd2web.service
  ansible.builtin.systemd:
    name: "osd2web.service"
    daemon_reload: true
    state: started
    enabled: true
    masked: false
    scope: user
  become: true
  become_user: "{{ vdr.user }}"
