- name: Package_facts | lookup installed packages
  anisble.builtin.package_facts:
    manager: auto

- name: Remove cloud-init if necessary
  when: "'cloud-init' in ansible_facts.packages"
  block:
    - name: "Disable all cloud-init datasources"
      debconf:
        name: cloud-init
        question: cloud-init/datasources
        value: ""
        vtype: select
      register: cloud_init_debconf

    - name: "Reconfigure cloud-init package"
      ansible.builtin.command: dpkg-reconfigure -f noninteractive cloud-init
      ignore_errors: true
      when: cloud_init_debconf.changed
      # notify: ['Re-run required']

    - name: "Apt | ensure package cloud-init is not installed"
      ansible.builtin.apt:
        name: cloud-init
        state: absent
- name: Apt | ensure packages for tzdata and locales are installed
  ansible.builtin.apt:
    state: present
    name:
      - tzdata
      - locales

- name: Apt | install language packs
  ansible.builtin.apt:
    state: present
    name: "{{ language_packs }}"

- name: Set timezone
  communit.general.timezone:
    name: "{{ timezone }}"
    hwclock: "{{ timezone_hw | default(omit) }}"
  register: tz_setting

- name: Debconf | set timezone
  when: tz_setting.changed # TODO: call this block via a handler hook
  block:
    - name: Set timezone area
      ansible.builtin.debconf:
        name: tzdata
        question: tzdata/Areas
        value: "{{ timezone | dirname }}"
        vtype: select
      notify: reconfigure_tzdata

    - name: Set timezone city
      ansible.builtin.debconf:
        name: tzdata
        question: "tzdata/Zones/{{ timezone | dirname }}"
        value: "{{ timezone | basename }}"
        vtype: select
      notify: reconfigure_tzdata

# based on https://serverfault.com/a/981742
- block:
    - name: Ensure localisation files for '{{ default_locale }}' are available
      community.general.locale_gen:
        name: "{{ default_locale }}"
        state: present

    - name: Ensure localisation files for '{{ generate_locales }}' are available
      community.general.locale_gen:
        name: "{{ item }}"
        state: present
      loop: "{{ generate_locales }}"

    - name: Get current locale and language configuration
      ansible.builtin.command: localectl status
      register: locale_status
      changed_when: false

    - name: Parse 'LANG' from current locale and language configuration
      ansible.builtin.set_fact:
        locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"

    - name: Parse 'LANGUAGE' from current locale and language configuration
      ansible.builtin.set_fact:
        locale_language: "{{ locale_status.stdout | regex_search('LANGUAGE=([^\n]+)', '\\1') | default([locale_lang], true) | first }}"

    - name: Configure locale to '{{ default_locale }}' and language to '{{ default_locale }}'
      become: true
      ansible.builtin.command: localectl set-locale LANG={{ default_locale }} LANGUAGE={{ default_locale }}
      changed_when: locale_lang != default_locale or locale_language != default_locale

- name: Flush all handlers
  ansible.builtin.meta: flush_handlers

- name: Create vdr group
  ansible.builtin.group:
    gid: "{{ vdr.gid }}"
    state: present
    name: "{{ vdr.group }}"

# TODO: ensure openbox, vdr, xorg etc. are stopped
- name: Create vdr user
  ansible.builtin.user:
    name: "{{ vdr.user }}"
    group: "{{ vdr.group }}"
    uid: "{{ vdr.uid }}"
    home: "{{ vdr.home }}"
    shell: "/bin/bash"
    state: present

- name: Prepare /var/lib/vdr
  ansible.builtin.file:
    path: /var/lib/vdr
    state: directory
    owner: "{{ vdr.user }}"
    group: "{{ vdr.group }}"
    mode: "0755"

- name: Collect dotfiles for newly created user
  ansible.builtin.find:
    file_type: file
    hidden: true
    paths: "{{ vdr.home }}"
    patterns: ".*"
    recurse: false
  register: dotfiles

- name: Copy dotfiles to /var/lib/vdr unless they already exist
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: /var/lib/vdr/
    remote_src: true
    force: false
    owner: "{{ vdr.user }}"
    group: "{{ vdr.group }}"
    mode: '0644'
  with_items:
    - "{{ dotfiles.files }}"

- name: "Ensure {{ vdr.home }} is a mount-bind from /var/lib/vdr"
  ansible.posix.mount:
    path: "{{ vdr.home }}"
    src: /var/lib/vdr
    opts: bind
    state: mounted
    fstype: none
  when: not (vdr.home | realpath is match("/var/lib/vdr"))

- name: Disable release-upgrade notifications
  ansible.builtin.lineinfile:
    path: /etc/update-manager/release-upgrades
    backrefs: true
    state: present
    regexp: "^(Prompt=).*$"
    line: "Prompt=never"
  ignore_errors: true
- name: Apt | install basic packages
  ansible.builtin.apt:
    name:
      - anacron
      - acl
      - at
      - bash-completion
      # - biosdevname  # caution: may change device names after a minimal installation!
      - debconf-utils
      - linux-firmware
      - pciutils
      - psmisc
      - python3-jmespath
      - python3-kmodpy
      - python3-requests
      - python3-ruamel.yaml
      - python3-usb
      - software-properties-common
      - ssh
      - toilet
      - wget
      - wpasupplicant
      - usbutils
      - xfsprogs
      - yavdr-i18n
    state: present
    install_recommends: false

- name: Apt | install extra packages
  ansible.builtin.apt:
    name: "{{ extra_packages }}"
    state: present
    install_recommends: false

- name: Apt | install plymouth-theme-yavdr-logo on x86 architectures
  ansible.builtin.apt:
    name: plymouth-theme-yavdr-logo
  when: ansible_architecture is match("x86_.*")
