---

- name: Import task files
  ansible.builtin.import_tasks:
    file: {{ item }}
  loop:
    - configure_apt.yml
    - configure_system.yml
    - create_directories.yml
    - create_sudoers.yml
    - standby_support.yml
  tags: [install]
