- name: Create /usr/local/bin/module-helper
  ansible.builtin.template:
    src: templates/module-helper.j2
    dest: /usr/local/bin/module-helper
    mode: '0755'

- name: Create standby hooks /lib/systemd/system-sleep/yavdr
  ansible.builtin.template:
    src: templates/system-sleep_yavdr.j2
    dest: /lib/systemd/system-sleep/yavdr
    mode: '0755'
