---
# this playbook sets up network services for a yaVDR installation

- name: Apt | install packages for network services
  ansible.builtin.apt:
    name:
      - avahi-daemon
      - avahi-utils
      - autofs
      # - biosdevname # caution: this may change device names after a minimal installation!
      - ethtool
      - nfs-common
      - vdr-addon-avahi-linker
      - wakeonlan
    state: present
    install_recommends: false

# Does this really work? We need a way to check if an interface supports WOL - Python Skript?
# - name: check WOL capabilities of network interfaces
#   shell: 'ethtool {{ item }} | grep -Po "(?<=Supports\sWake-on:\s).*$"'
#   register: wol
#   with_items: '{% for interface in ansible_interfaces if interface != 'lo' and interface != 'bond0' %}'

- name: Make local domain name resolution work with systemd-networkd
  community.general.ini_file:
    path: /etc/systemd/networkd.conf
    section: Network
    option: UseDomains
    value: 'yes'
    backup: true
    mode: '0644'

- name: Restart systemd-networkd.service
  ansible.builtin.systemd:
    name: systemd-networkd.service
    state: restarted

- name: Restart autofs if running
  ansible.builtin.systemd:
    name: autofs
    state: restarted
    enabled: true
    masked: false

- name: Ensure autofs is running
  ansible.builtin.systemd:
    name: autofs
    state: started
    enabled: true
    masked: false

- name: Set video directory for avahi-linker
  community.general.ini_file:
    path: /etc/avahi-linker/default.cfg
    section: "targetdirs"
    option: "vdr"
    value: "{{ vdr.recdir }}"
    mode: '0644'

- name: Set vdr instance id for avahi-linker
  community.general.ini_file:
    path: /etc/avahi-linker/default.cfg
    section: "options"
    option: "vdr_instance_id"
    value: "{{ vdr.instance_id | default(0) }}"
    mode: '0644'

- name: Restart avahi-linker if running
  ansible.builtin.systemd:
    name: avahi-linker
    state: restarted
    enabled: true
    masked: false

- name: Ensure avahi-linker is started
  ansible.builtin.systemd:
    name: avahi-linker
    state: started
    enabled: true
    masked: false

# - name: Ensure additional services for avahi-linker are active
#   ansible.builtin.systemd:
#     name: '{{ item }}'
#     state: started
#     enabled: true
#     masked: false
#   loop:
#     - vdr-net-monitor
#     - vdr-update-monitor
# - uprevent-umount-on-pause
