---
# file roles/autoinstall-satip/tasks/main.yml

- name: "Detect SAT>IP Server(s) on the network"
  action: satip_facts

- name: Show satip_devices
  ansible.builtin.debug:
    var: ansible_facts.satip_devices
    verbosity: 1

- name: Apt | install vdr-plugin-satip if a Sat>IP server has been detected
  ansible.builtin.apt:
    name: vdr-plugin-satip
    state: present
  when: ansible_facts.satip_devices | length > 0
  notify: ['Restart VDR']
