---
# file roles/autoinstall-satip/tasks/main.yml

- name: "detect SAT>IP Server(s) on the network"
  action: satip_facts

- debug:
    var: satip_devices
    verbosity: 1

- name: apt | install vdr-plugin-satip if a Sat>IP server has been detected
  apt:
    name: vdr-plugin-satip
    state: present
  when: satip_devices | length > 0
  notify: [ 'Restart VDR' ]

- name: copy file | satip.conf if a Sat>IP server has been detected
  template:
    src: templates/satip.conf.j2
    dest: /etc/vdr/conf.avail/satip.conf
    owner: root
    group: root
    mode: 0644
  when: satip_devices | length > 0
  notify: [ 'Restart VDR' ]
