- name: Reconfigure unattended upgrades with dpkg
  ansible.builtin.command: '/usr/sbin/dpkg-reconfigure --frontend falseninteractive unattended-upgrades'
  changed_when: true

- name: Trigger Udev
  ansible.builtin.command: 'udevadm trigger'
  changed_when: true

- name: Reload Units
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Samba
  ansible.builtin.systemd:
    name: smbd.service
    state: restarted
    enabled: true
    # masked: false
  register: samba_reload

- name: Restart vdr-addon-lifeguard-ng
  ansible.builtin.systemd:
    name: vdr-addon-lifeguard-ng.service
    state: restarted
    enabled: true
  register: lifeguard_reload

- name: Restart NFS Kernel Server
  ansible.builtin.systemd:
    name: nfs-server.service
    state: restarted
    enabled: true
    # masked: false
  register: nfs_reload

- name: Restart sundtek.service
  ansible.builtin.systemd:
    name: sundtek.service
    state: restarted
    enabled: true
    masked: false

- name: Restart VDR
  ansible.builtin.systemd:
    name: vdr.service
    state: restarted
    enabled: true
    daemon_reload: true
  register: vdr_restart

- name: Stop VDR
  ansible.builtin.systemd:
    name: vdr.service
    state: stopped
    enabled: true
  register: vdr_stop

- name: Start VDR
  ansible.builtin.systemd:
    name: vdr.service
    state: started
    enabled: true
    daemon_reload: true
  register: vdr_start

- name: Start yavdr-xorg
  ansible.builtin.systemd:
    daemon_reload: true
    name: 'yavdr-xorg'
    enabled: true
    state: started
  register: yavdr_xorg_start


- name: Stop yavdr-xorg
  ansible.builtin.service:
    name: yavdr-xorg
    state: stopped
    enabled: false
  register: yavdr_xorg_stop

- name: Stop xlogin
  ansible.builtin.systemd:
    name: xlogin@vdr.service
    state: stopped
    enabled: true
  register: xlogin_stop

- name: Start xlogin
  ansible.builtin.systemd:
    daemon_reload: true
    name: 'xlogin@{{ vdr.user }}'
    enabled: true
    state: started
  register: xlogin_start

- name: Start x@vt7.service
  ansible.builtin.systemd:
    name: x@vt7.service
    enabled: true
    state: started
  register: x_stop

- name: Reboot required
  ansible.builtin.debug:
    msg: PLEASE REBOOT YOUR SYSTEM.

- name: Re-run required
  ansible.builtin.debug:
    msg: PLEASE REBOOT YOUR SYSTEM AND RUN THIS PLAYBOOK AGAIN.
