- name: Apt | install dependencies
  ansible.builtin.apt:
    name:
      - git
      - python3-lxml
    state: present

- name: Copy channel_linker script
  ansible.builtin.template:
    src: roles/channellogos/templates/channel_linker.py.j2
    dest: /usr/local/bin/channel_linker
    mode: '0755'

- name: Get mediaportal channel logos
  ansible.builtin.git:
    repo: "https://github.com/Jasmeet181/mediaportal-{{ item }}-logos.git"
    dest: "/usr/local/lib/mediaportal-{{ item }}-logos"
    clone: true
    depth: 1
    update: true
  loop: "{{ channellogos_languages }}"

- name: Update channel logo links
  ansible.builtin.command: /usr/local/bin/channel_linker {{ channellogos_languages | map('quote') | join(' ') }}
  changed_when: true


# TODO: use picon logos: https://github.com/picons/picons