---
# file roles/autoinstall-dvbsddevice/tasks/main.yml

# TODO: install firmware

- name: Install firmware and output plugin for FF sd cards
  when: '"dvb_ttpci" in modules or force_dvbsddevice|default(False)|bool'
  block:
    - name: Download firmware files
      ansible.builtin.get_url:
        url: '{{ item.src }}'
        dest: '/lib/firmware/{{ item.name }}'
        checksum: '{{ item.checksum }}'
        mode: '0755'
      loop: "{{ dvbsddevice_firmware }}"
      notify: ['Reboot required']

    - name: Apt | install vdr-plugin-dvbsddevice if module is loaded
      ansible.builtin.apt:
        name: vdr-plugin-dvbsddevice
      notify: ['Restart VDR']
