---
# file roles/autoinstall-imonvfd/tasks/main

- name: Set up IMON VFD
  when: '"15c2:0036" in usb or "15c2:0044" in usb'
  block:
    - name: Check which display type we got
      ansible.builtin.set_fact:
        imon_vfd_device: '{{ "imon_0044" if "15c2:0044" in ansible_facts.usb else "imon_0036" }}'
    - name: Apt | install lcdproc and vdr-plugin-lcdproc for IMON VFD
      ansible.builtin.apt:
        name: vdr-plugin-lcdproc

    - name: Copy udev rule for IMON VFD
      ansible.builtin.template:
        src: templates/92-imonvfd.rules.j2
        dest: /etc/udev/rules.d/92-imonvfd.rules
        mode: '0644'
        force: true
      notify: ['Reboot required']

    - name: Expand template for /etc/LCDd.conf
      ansible.builtin.template:
        src: templates/LCDd.conf.j2
        dest: /etc/LCDd.conf
        owner: root
        group: root
        mode: '0644'
        force: true

    - name: Enable service LCDd.service and ensure it is not masked
      ansible.builtin.systemd:
        name: LCDd.service
        state: started
        enabled: true
        masked: false
        daemon_reload: true

