---
- name: Create kodi.service for the user session
  ansible.builtin.template:
      src: 'templates/kodi.service.j2'
      dest: '{{ vdr.home }}/.config/systemd/user/kodi.service'
      mode: '0644'
      owner: '{{ vdr.user }}'
      group: '{{ vdr.group }}'

- name: Create kodi user directory
  ansible.builtin.file:
      dest: '{{ kodi_config_dir }}/userdata/keymaps'
      state: directory
      owner: '{{ vdr.user }}'
      group: '{{ vdr.group }}'
      mode: "0775"
      recurse: true

- name: Copy Lircmap.xml if it does not exist yet
  ansible.builtin.copy:
      dest: '{{ kodi_config_dir }}/userdata/Lircmap.xml'
      src: 'files/userdata/Lircmap.xml'
      owner: '{{ vdr.user }}'
      group: '{{ vdr.group }}'
      mode: "0664"
      force: false

- name: Copy remote.xml if it does not exist yet
  ansible.builtin.copy:
      dest: '{{ kodi_config_dir }}/userdata/keymaps/remote.xml'
      src: 'files/userdata/keymaps/remote.xml'
      owner: '{{ vdr.user }}'
      group: '{{ vdr.group }}'
      mode: "0664"
      force: false

- name: Expand template for set-kodi-display
  ansible.builtin.template:
      src: 'templates/set-kodi-display.j2'
      dest: '/usr/bin/set-kodi-display'
      mode: "0755"

- name: Set flatpak permissions for kodi to access media directories
  when: kodi_as_flatpak
  block:
      - name: Get output for current permissions
        ansible.builtin.command: /usr/bin/flatpak --user override --show tv.kodi.Kodi
        become: true
        become_user: vdr
        register: kodi_permissions_output
        changed_when: false

      - name: Determine folders to add to the kodi flatpak configuration
        ansible.builtin.set_fact:
            kodi_permissions_to_add: |
             {{ flatpak_kodi_allowed_dirs | difference(
                   (
                     kodi_permissions_output.stdout_lines |
                     select('match', '^filesystems=') |
                     first | default('') |
                     regex_search('(?<=filesystems=).*') | default('', true)
                   ).split(';') | select() | default([])) | list
             }}

      - name: Set kodi flatpak directory access permissions
        ansible.builtin.command: '/usr/bin/flatpak --user override --filesystem="{{ item }}" tv.kodi.Kodi'
        become: true
        become_user: vdr
        loop: "{{ kodi_permissions_to_add }}"
        when: kodi_permissions_to_add | length > 0
