- name: Import tasks to install KODI
  ansible.builtin.import_tasks: install-kodi.yml
  tags:
    - install
    - update
    - kodi:install
- name: Import tasks to configure KODI
  ansible.builtin.import_tasks: configure-kodi.yml
  tags:
    - install
    - update
    - kodi:configure
