- name: Show vdr_output_plugin
  ansible.builtin.debug:
    var: vdr_output_plugin
    verbosity: 1

- name: Show automatically_installed_output_plugin
  ansible.builtin.debug:
    var: automatically_installed_output_plugin
    verbosity: 1

- name: Apt | install the output plugin
  ansible.builtin.apt:
    state: present
    name: '{{ vdr_output_plugin }}'

- name: Show selected_frontend
  ansible.builtin.debug:
    var: selected_frontend
    verbosity: 1

- name: Show preferred_frontend
  ansible.builtin.debug:
    var: preferred_frontend
    verbosity: 1

- name: Set active output plugin
  ansible.builtin.set_fact:
    active_output_plugin: '{{ selected_frontend }}'

- name: Show active_output_plugin
  ansible.builtin.debug:
    msg: 'active_output_plugin is: {{ active_output_plugin }}'
    verbosity: 1

- name: Set disabled output plugins
  ansible.builtin.set_fact:
    disabled_output_plugins: '{{ known_output_plugins | difference([active_output_plugin]) | list }}'
  when: active_output_plugin | length > 0

- name: Show disabled_output_plugins
  ansible.builtin.debug:
    var: q('list', disabled_output_plugins)
    verbosity: 1

- name: Disable unused output plugins
  ansible.builtin.command: "vdrctl disable {{ item }}"
  loop: '{{ disabled_output_plugins }}'
  register: vdrctl
  failed_when: false # vdrctl.rc != 0 and 'is unknown or already disabled' not in vdrctl.stderr
  changed_when: true # TODO: check file/symlink
  when: disabled_output_plugins is defined

- name: Enable chosen output plugin
  ansible.builtin.command: vdrctl enable {{ active_output_plugin }}
  register: vdrctl
  failed_when:
    - vdrctl.rc != 0 and 'is already linked to' not in vdrctl.stderr
  changed_when: true # TODO: check file/symlink
  when: active_output_plugin | length > 0
