- name: Reconfigure_tzdata
  ansible.builtin.command: >
      dpkg-reconfigure --frontend noninteractive tzdata

- name: Reconfigure_locales
  ansible.builtin.command: >
      dpkg-reconfigure --frontend noninteractive locales

- name: Reconfigure_dash
  ansible.builtin.command: >
      dpkg-reconfigure -f noninteractive dash
