yavdr_ansible_git_repo: https://github.com/yavdr/yavdr-ansible.git
yavdr_ansible_git_branch: devel
yavdr_ansible_path: /var/lib/yavdr-ansible/project

# if the user overrides those values, they will be copied
custom_ssl_cert_local_path: ""
custom_ssl_key_local_path: ""

# target path for nginx
nginx_ssl_cert_path: "/etc/ssl/certs/nginx-selfsigned.crt"
nginx_ssl_key_path: "/etc/ssl/private/nginx-selfsigned.key"