---
# file roles/autoinstall-imonlcd/tasks/main.yml

- name: Apt | install vdr-plugin-imonlcd if connected
  ansible.builtin.apt:
    name: vdr-plugin-imonlcd
  when: '"15c2:0038" in usb or "15c2:ffdc" in usb'
  notify: ['Restart VDR']
