---
# file roles/autoinstall-targavfd/tasks/main.yml

- name: Apt | install vdr-plugin-targavfd if connected
  ansible.builtin.apt:
    name: vdr-plugin-targavfd
  when: '"19c2:6a11" in ansible_facts.usb'
  notify: ['Restart VDR']
