---
- name: Apt | remove pulseaudio
  ansible.builtin.apt:
    name:
      - pulseaudio
      - yavdr-pasuspend
    state: absent
    install_recommends: false

- name: Apt | install pipewire, pavucontrol and vdr-plugin-pulsecontrol
  ansible.builtin.apt:
    name:
      - alsa-base
      - alsa-utils
      - pipewire
      - pipewire-alsa
      - pipewire-audio
      - pipewire-pulse
      - wireplumber
      - pavucontrol
      - python3-pulsectl
      - python3-dasbus
      - rtkit
      - vdr-plugin-pulsecontrol
      - yavdr-pulse-dbusctl
    state: present
    install_recommends: false

- name: Ensure /var/lib/vdr/plugins/pulsecontrol/ exists
  ansible.builtin.file:
    name: /var/lib/vdr/plugins/pulsecontrol
    state: directory
    owner: "{{ vdr.user }}"
    group: "{{ vdr.group }}"
    mode: "0755"

- name: Create /var/lib/vdr/plugins/pulsecontrol/startup.script
  ansible.builtin.file:
    name: /var/lib/vdr/plugins/pulsecontrol/startup.script
    state: touch
    mode: "0755"

- name: Create /etc/asound.conf with pipewire as default device
  ansible.builtin.template:
    src: templates/alsa/asound.conf.j2
    dest: /etc/asound.conf
    mode: "0644"

- name: "Create/Update /etc/dbus-1/system.d/org.yavdr.dbus_pulse_ctl.conf to configure access to dbus_pulsectl"
  ansible.builtin.template:
    src: "dbus_pulsectl/org.yavdr.dbus_pulsectl.conf.j2"
    dest: "/etc/dbus-1/system.d/org.yavdr.dbus_pulse_ctl.conf"
    mode: "0644"

- name: Ensure ~/bin exists for vdr user
  ansible.builtin.file:
    path: "{{ vdr.home }}/bin"
    owner: "{{ vdr.user }}"
    group: "{{ vdr.group }}"
    state: directory
    mode: "0755"

- name: Ensure ~/.config/systemd/user exists for vdr user
  ansible.builtin.file:
    path: "{{ vdr.home }}/.config/systemd/user"
    state: directory
    owner: "{{ vdr.user }}"
    group: "{{ vdr.group }}"
    mode: "0755"
    recurse: false
    # TODO: better way to enable unit than in openbox autostart set by yavdr-desktop?

- name: Allow alsamixer to work by extending the apparmor rules
  ansible.builtin.blockinfile:
    path: /etc/apparmor.d/local/alsamixer
    create: true
    mode: '0644'
    block: |
          # allow accessing asound.conf to make alsamixer work
          /etc/asound.conf r,
  notify: Reload AppArmor

- name: Hint that the pipewire role was enabled
  ansible.builtin.set_fact:
    pipewire_installed: true
