---
# This role is used to set up the yaVDR remote control configuration.

- name: Apt | install packages for remote support
  ansible.builtin.apt:
    name:
      - yavdr-remote
      - lirc
    state: present
  tags:
    - packages

- name: Add systemd drop-in for lircd to use lircd2uinput
  tags:
    - config
  block:
    - name: Create directory /etc/systemd/system/lircd.service.d/
      ansible.builtin.file:
        path: /etc/systemd/system/lircd.service.d/
        state: directory
        mode: '0644'

    - name: Expand template for /etc/systemd/system/lircd.service.d/lircd2uinput.conf
      ansible.builtin.template:
        src: templates/lircd.service.d/lircd2uinput.conf.j2
        dest: /etc/systemd/system/lircd.service.d/lircd2uinput.conf
        mode: '0644'
      notify: ["Reload Units"]

- name: Stop, mask and disable lircd.socket, lircd.service, lircmd.service and lircd-uinput.service # (the default lirc configuration conflicts with eventlircd)
  tags:
    - systemd
  ansible.builtin.systemd:
    name: '{{ item }}'
    enabled: false
    state: stopped
    masked: true
  loop:
    - lircd.service
    - lircd.socket
    - lircmd.service
    - lircd-uinput.service
  ignore_errors: true

- name: Apt | install eventlircd and lircd2uinput
  ansible.builtin.apt:
    name:
      - eventlircd
      - lircd2uinput
    state: present
  tags:
    - packages

- name: Configure vdr to read from a lircd-compatible socket
  ansible.builtin.template:
    src: templates/03-vdr-lirc.conf.j2
    dest: /etc/vdr/conf.d/03-vdr-lirc.conf
    mode: '0644'
  notify: ['Restart VDR']
  tags:
    - config

- name: Expand template for /etc/rc_maps.cfg
  ansible.builtin.template:
    src: templates/rc_maps.cfg.j2
    dest: /etc/rc_maps.cfg
    mode: '0644'
  notify: ['Trigger Udev']
  tags:
    - config


- name: Install dependencies for rc-core-learn.py
  ansible.builtin.apt:
    pkg:
      - python3-evdev
    state: present

- name: Expand template for rc-core-learn.py
  ansible.builtin.template:
    src: templates/rc-core-learn.py.j2
    dest: /usr/local/bin/rc-core-learn
    mode: '0755'
