---
# file: roles/yavdr-xorg/tasks/desktop-session.yml

- name: Create folders for user configuration files
  ansible.builtin.file:
    state: directory
    dest: '{{ item }}'
    owner: '{{ vdr.user }}'
    group: '{{ vdr.group }}'
    mode: '0775'
  with_items:
    - '{{ vdr.home }}/.config/systemd/user'
    - '{{ vdr.home }}/.config/openbox'
    - '{{ vdr.home }}/.config/pulse'

- name: Expand template for .xinitrc for vdr user
  ansible.builtin.template:
    src: 'templates/.xinitrc.j2'
    dest: '{{ vdr.home }}/.xinitrc'
    mode: '0755'
    owner: '{{ vdr.user }}'
    group: '{{ vdr.group }}'

- name: "Expand template for vdr's .Xresources"
  ansible.builtin.template:
    src: 'templates/.Xresources.j2'
    dest: '{{ vdr.home }}/.Xresources'
    mode: '0644'
    owner: '{{ vdr.user }}'
    group: '{{ vdr.group }}'

- name: Expand template for openbox autostart
  ansible.builtin.template:
    src: 'templates/openbox/autostart.j2'
    dest: '{{ vdr.home }}/.config/openbox/autostart'
    mode: '0755'
    owner: '{{ vdr.user }}'
    group: '{{ vdr.group }}'

- name: Expand rc.xml for openbox
  ansible.builtin.template:
    src: 'templates/openbox/rc.xml.j2'
    dest: '{{ vdr.home }}/.config/openbox/rc.xml'
    mode: '0644'
    owner: '{{ vdr.user }}'
    group: '{{ vdr.group }}'

- name: Create yavdr-desktop.target for the user session
  ansible.builtin.template:
    src: 'templates/systemd/user/yavdr-desktop.target.j2'
    dest: '{{ vdr.home }}/.config/systemd/user/yavdr-desktop.target'
    mode: '0644'
    owner: '{{ vdr.user }}'
    group: '{{ vdr.group }}'

- name: Disable pulseaudio autospawning
  ansible.builtin.lineinfile:
    path: '{{ vdr.home }}/.config/pulse/client.conf'
    line: 'autospawn = yes'
    create: true
    state: present
    owner: '{{ vdr.user }}'
    group: '{{ vdr.group }}'
    mode: '0644'

- name: Create tmux.service for the session
  ansible.builtin.template:
    src: roles/yavdr-xorg/templates/systemd/user/tmux.service.j2
    dest: '{{ vdr.home }}/.config/systemd/user/tmux.service'
    mode: '0644'
    owner: '{{ vdr.user }}'
    group: '{{ vdr.group }}'

- name: Create wm-exit.service for the session
  ansible.builtin.template:
    src: roles/yavdr-xorg/templates/systemd/user/wm-exit.service.j2
    dest: '{{ vdr.home }}/.config/systemd/user/wm-exit.service'
    mode: '0644'
    owner: '{{ vdr.user }}'
    group: '{{ vdr.group }}'

- name: Create detect-second-display.service for the session
  ansible.builtin.template:
    src: templates/systemd/user/detect-second-display.service.j2
    dest: '{{ vdr.home }}/.config/systemd/user/detect-second-display.service'
    mode: '0644'
    owner: '{{ vdr.user }}'
    group: '{{ vdr.group }}'

- name: Create openbox-second.service for the session
  ansible.builtin.template:
    src: templates/systemd/user/openbox-second.service.j2
    dest: '{{ vdr.home }}/.config/systemd/user/openbox-second.service'
    mode: '0644'
    owner: '{{ vdr.user }}'
    group: '{{ vdr.group }}'

- name: Create osd2web.service for the session
  ansible.builtin.template:
    src: templates/systemd/user/osd2web.service.j2
    dest: '{{ vdr.home }}/.config/systemd/user/osd2web.service'
    owner: '{{ vdr.user }}'
    group: '{{ vdr.group }}'
    mode: '0644'


- name: Create irexec configuration for the session
  block:
    - name: Expand template for irexec.service
      ansible.builtin.template:
        src: templates/systemd/user/irexec.service.j2
        dest: '{{ vdr.home }}/.config/systemd/user/irexec.service'
        mode: '0644'
        owner: '{{ vdr.user }}'
        group: '{{ vdr.group }}'
    - name: Expand template for .lircrc
      ansible.builtin.template:
        src: templates/.lircrc.j2
        dest: '{{ vdr.home }}/.lircrc'
        mode: '0644'
        owner: '{{ vdr.user }}'
        group: '{{ vdr.group }}'

- name: Link /usr/bin/start-desktop to /var/lib/vdr/plugins/desktop/starter
  ansible.builtin.file:
    src: /usr/bin/start-desktop
    dest: /var/lib/vdr/plugins/desktop/starter
    state: link

- name: Enable and start xlogin for the vdr user
  ansible.builtin.systemd:
    daemon_reload: true
    name: 'xlogin@{{ vdr.user }}'
    enabled: true
    state: started
