---
# file: roles/yavdr-xorg/tasks/detect-xorg.yml

- name: Stop VDR
  ansible.builtin.systemd:
    name: vdr.service
    state: stopped
    enabled: true
  notify: ["Start VDR"]

- name: Stop yavdr-xorg
  ansible.builtin.systemd:
    name: "yavdr-xorg.service"
    state: stopped
    enabled: true
  notify: ["Start yavdr-xorg"]

- name: Check if /etc/yavdr/display_config exists
  ansible.builtin.stat:
    path: /etc/yavdr/display_config
  register: custom_display_config_file

- name: Backup /etc/yavdr/display_config
  ansible.builtin.copy:
    src: /etc/yavdr/display_config
    dest: /etc/yavdr/display_config.backup
    mode: "0644"
    remote_src: true
  when: custom_display_config_file.stat.exists

- name: Remove /etc/yavdr/display_config
  ansible.builtin.file:
    path: /etc/yavdr/display_config
    state: absent
  when: custom_display_config_file.stat.exists

- name: "Expand template for x-verbose@.service"
  ansible.builtin.template:
    src: "templates/systemd/system/x-verbose@.service.j2"
    dest: "/etc/systemd/system/x-verbose@.service"
    mode: "0644"
  notify: ["Reload Units"]

- name: "Expand template for xorg-verbose.conf"
  ansible.builtin.template:
    src: "templates/xorg-verbose.conf.j2"
    dest: "/etc/X11/xorg-verbose.conf"
    mode: "0644"

- name: "Remove Intel snippet"
  ansible.builtin.file:
    path: /etc/X11/xorg.conf.d/20-intel.conf
    state: absent

- name: Remove AMD snippet
  ansible.builtin.file:
    path: /etc/X11/xorg.conf.d/20-amd.conf
    state: absent

- name: Check /etc/yavdr/autoinstalled if a nvidia driver has been installed
  ansible.builtin.lineinfile:
    name: /etc/yavdr/autoinstalled
    regexp: ".*nvidia.*"
    state: absent
  check_mode: true
  register: nvidia_driver_detected

- name: Set_fact | nvidia_driver_installed
  ansible.builtin.set_fact:
    nvidia_driver_installed: "{{ nvidia_driver_detected.changed | bool }}"

- name: Unload nouveau driver, replace with nvidia
  when:
    - nvidia_detected | bool
    - nvidia_driver_installed | bool
    - '"nouveau" in ansible_facts.modules'
  block:
    - name: Unbind vconsole
      ansible.builtin.shell: "echo 0 > /sys/class/vtconsole/vtcon1/bind"
      changed_when: true # TOOD better check

    - name: "Wait a little, so noveau isn't used anymore"
      ansible.builtin.wait_for:
        timeout: 1

    # unloading the drivers using the modprobe module does not work for some strange reason...
    - name: Unload kms drivers
      rmmod:
        name: "{{ item }}"
      loop:
        - nouveau
        - ttm
        - drm_kms_helper
        - drm

    - name: Load nvidia driver
      community.general.modprobe:
        name: "nvidia"
        state: present

    - name: "Wait a little before starting nvidia-persistenced"
      ansible.builtin.wait_for:
        timeout: 1

    - name: Start nvidia-persistenced
      ansible.builtin.systemd:
        name: "nvidia-persistenced"
        state: started
        enabled: true
        masked: false
        daemon_reload: true
      failed_when: false

- name: "Start x-verbose@.service"
  ansible.builtin.systemd:
    name: "x-verbose@vt7.service"
    state: started
    enabled: false
    masked: false
    daemon_reload: true

- name: "Wait a little, so X has some time to start up"
  ansible.builtin.wait_for:
    timeout: 3

- name: "Detect connected monitors"
  display_facts:
    preferred_refreshrates: "{{ preferred_refreshrates }}"
    preferred_resolutions: "{{ preferred_resolutions }}"
    preferred_outputs: "{{ preferred_outputs }}"

- name: "Stop x-verbose@vt7.service"
  ansible.builtin.systemd:
    name: "x-verbose@vt7.service"
    state: stopped
    enabled: false
    masked: true

- name: Show result of graphics_facts
  ansible.builtin.debug:
    msg: |
      display_outputs={{ ansible_facts["display_outputs"] | default("undefined") }}
      display_config={{ ansible_facts["display_config"] | default("undefined") }}

- name: Save result of graphics_facts module
  block:
    - name: Ensure facts.d directory exists
      ansible.builtin.file:
        state: directory
        path: /etc/ansible/facts.d
        mode: "0755"

    - name: Write display_outputs variable as local fact
      ansible.builtin.copy:
        content: '{{ {"connectors": ansible_facts.display_outputs | default({})} | to_nice_json }}'
        dest: /etc/ansible/facts.d/display_outputs.fact
        mode: "0644"

    - name: Write display_config variable as local fact
      ansible.builtin.copy:
        content: '{{ ansible_facts.display_config | default({"primary": null, "secondary": null}) | to_nice_json }}'
        dest: /etc/ansible/facts.d/display_config.fact
        mode: "0644"

- name: Check if nvidia-smi is installed
  ansible.builtin.command: nvidia-smi
  register: nvidia_smi
  changed_when: false
  failed_when: false

- name: Set nvidia_driver_detected variable
  ansible.builtin.set_fact:
    nvidia_driver_installed: "{{ nvidia_smi.rc == 0 | bool | default(false) }}"

- name: VDR-config | create softhddevice.conf if it doesn't exist yet
  ansible.builtin.lineinfile:
    path: /etc/vdr/conf.avail/softhddevice.conf
    create: true
    state: present
    mode: "0644"
    line: "[softhddevice]"

- name: VDR-config | start softhddevice detached and set audio to pulseaudio
  ansible.builtin.lineinfile:
    path: /etc/vdr/conf.avail/softhddevice.conf
    line: "{{ item }}"
  loop:
    - "-D"
    - "-w alsa-driver-broken"
    # - '-a pulse' # do we need this with our existing asound.conf?

- name: VDR-config | set vaapi video output method for softhddevice
  ansible.builtin.lineinfile:
    path: /etc/vdr/conf.avail/softhddevice.conf
    state: present
    regexp: "^-v .*"
    line: "-v {{ softhddevice_vaapi_output_method | default('va-api-egl') }}"
  when: (intel_detected or amd_detected or (nvidia_detected and not nvidia_driver_installed))

- name: VDR-config | set nvdec-egl video output method for softhddevice
  ansible.builtin.lineinfile:
    path: /etc/vdr/conf.avail/softhddevice.conf
    state: present
    regexp: "^-v .*"
    line: "-v nvdec-egl"
  when: (ansible_facts.nvidia_detected and nvidia_driver_installed)


- name: Configure vdr-plugin-vaapivideo
  when: (selected_frontend | default("softhddevice") == "vaapivideo")
  block:
    - name: VDR-config | create vaapivideo.conf if it doesn't exist yet
      ansible.builtin.lineinfile:
        path: /etc/vdr/conf.avail/vaapivideo.conf
        create: true
        state: present
        mode: "0644"
        line: "[vaapivideo]"

    - name: VDR-config | start vaapivideo detached
      ansible.builtin.lineinfile:
        path: /etc/vdr/conf.avail/vaapivideo.conf
        line: "{{ item }}"
      loop:
        - "-D"

- name: Write variables for detected hardware
  ansible.builtin.copy:
    content: '{{ {"nvidia_detected": ansible_facts.nvidia_detected, "nvidia_driver_installed": nvidia_driver_installed, "intel_detected": ansible_facts.intel_detected, "amd_detected": ansible_facts.amd_detected} | to_nice_json }}'
    dest: /etc/ansible/facts.d/hardware_detected.fact
    mode: "0644"
