---
# file: roles/yavdr-xorg/tasks/detect-xorg.yml

- name: Stop VDR
  ansible.builtin.systemd:
    name: vdr.service
    state: stopped
    enabled: true
  notify: ["Start VDR"]

- name: Stop yavdr-xorg
  ansible.builtin.systemd:
    name: "yavdr-xorg.service"
    state: stopped
    enabled: true
  notify: ["Start yavdr-xorg"]

- name: "Expand template for x-verbose@.service"
  ansible.builtin.template:
    src: "templates/systemd/system/x-verbose@.service.j2"
    dest: "/etc/systemd/system/x-verbose@.service"
    mode: "0644"
  notify: ["Reload Units"]

- name: "Expand template for xorg-verbose.conf"
  ansible.builtin.template:
    src: "templates/xorg-verbose.conf.j2"
    dest: "/etc/X11/xorg-verbose.conf"
    mode: "0644"

- name: "Remove Intel snippet"
  ansible.builtin.file:
    path: /etc/X11/xorg.conf.d/20-intel.conf
    state: absent

- name: Remove AMD snippet
  ansible.builtin.file:
    path: /etc/X11/xorg.conf.d/20-amd.conf
    state: absent

- name: Check /etc/yavdr/autoinstalled if a nvidia driver has been installed
  ansible.builtin.lineinfile:
    name: /etc/yavdr/autoinstalled
    regexp: ".*nvidia.*"
    state: absent
  check_mode: true
  register: nvidia_driver_detected

- name: Set_fact | nvidia_driver_installed
  ansible.builtin.set_fact:
    nvidia_driver_installed: "{{ nvidia_driver_detected.changed | bool }}"

- name: Unload nouveau driver, replace with nvidia
  when:
    - nvidia_detected | bool
    - nvidia_driver_installed | bool
    - '"nouveau" in ansible_facts.modules'
  block:
    - name: Unbind vconsole
      ansible.builtin.shell: "echo 0 > /sys/class/vtconsole/vtcon1/bind"
      changed_when: true # TOOD better check

    - name: "Wait a little, so noveau isn't used anymore"
      ansible.builtin.wait_for:
        timeout: 1

    # unloading the drivers using the modprobe module does not work for some strange reason...
    - name: Unload kms drivers
      rmmod:
        name: "{{ item }}"
      loop:
        - nouveau
        - ttm
        - drm_kms_helper
        - drm

    - name: Load nvidia driver
      community.general.modprobe:
        name: "nvidia"
        state: present

    - name: "Wait a little before starting nvidia-persistenced"
      ansible.builtin.wait_for:
        timeout: 1

    - name: Start nvidia-persistenced
      ansible.builtin.systemd:
        name: "nvidia-persistenced"
        state: started
        enabled: true
        masked: false
        daemon_reload: true
      failed_when: false

- name: "Start x-verbose@.service"
  ansible.builtin.systemd:
    name: "x-verbose@vt7.service"
    state: started
    enabled: false
    masked: false
    daemon_reload: true

- name: "Wait a little, so X has some time to start up"
  ansible.builtin.wait_for:
    timeout: 3

- name: "Detect xorg configuration"
  xrandr_facts:
    preferred_refreshrates: "{{ preferred_refreshrates }}"
    preferred_resolutions: "{{ preferred_resolutions }}"
    preferred_outputs: "{{ preferred_outputs }}"

- name: "Detect connected monitors"
  graphics_facts:
    preferred_refreshrates: "{{ preferred_refreshrates }}"
    preferred_resolutions: "{{ preferred_resolutions }}"
    preferred_outputs: "{{ preferred_outputs }}"

- name: Show parsed xrandr data
  ansible.builtin.debug:
    var: ansible_facts.xrandr

- name: Show primary display configuration
  ansible.builtin.debug:
    var: ansible_facts.xorg.primary

- name: Show secondary display configuration
  ansible.builtin.debug:
    var: ansible_facts.xorg.secondary
  when: ansible_facts.xorg.secondary is defined

- name: Show drm data (emtpy for some nvidia cards)
  ansible.builtin.debug:
    var: ansible_facts.drm
  when: ansible_facts.drm is defined

- name: Show xorg_config data
  ansible.builtin.debug:
    var: ansible_facts.XorgConfig
  when: ansible_facts.XorgConfig is defined

- name: "Stop x-verbose@vt7.service"
  ansible.builtin.systemd:
    name: "x-verbose@vt7.service"
    state: stopped
    enabled: false
    masked: true

# - name: "Wait a little bit, so X has some time to shut down (needed?)"
#   wait_for:
#     timeout: 3

- name: Show result of xorg_facts
  ansible.builtin.debug:
    msg: |
      xrandr={{ ansible_facts.xrandr | default('undefined') }}
      xorg={{ ansible_facts.xorg | default('undefined') }}
      drm={{ ansible_facts.drm | default('undefined') }}
      xorg_config={{ ansible_facts.xorg_config | default('undefined') }}

- name: Show result of graphics_facts
  ansible.builtin.debug:
    msg: |
      graphics_outpus={{ ansible_facts.graphics_outputs | default("undefined") }}
      graphics_config={{ ansible_facts.graphics_config | default("undefined") }}

- name: Save result of graphics_facts module
  block:
    - name: Ensure facts.d directory exists
      ansible.builtin.file:
        state: directory
        path: /etc/ansible/facts.d
        mode: "0755"

    - name: Write xorg variable as local fact
      ansible.builtin.copy:
        content: '{{ {"connectors": ansible_facts.graphics_outputs | default({})} | to_nice_json }}'
        dest: /etc/ansible/facts.d/graphics.fact
        mode: "0644"

    - name: Write graphics_config variable as local fact
      ansible.builtin.copy:
        content: '{{ {"graphics_config": ansible_facts.graphics_config | default({}) } | to_nice_json }}'
        dest: /etc/ansible/facts.d/graphics_config.fact
        mode: "0644"

- name: Save results of xorg_facts module
  block:
    - name: Ensure facts.d directory exists
      ansible.builtin.file:
        state: directory
        path: /etc/ansible/facts.d
        mode: "0755"

    - name: Write xorg variable as local fact
      ansible.builtin.copy:
        content: '{{ {"xorg": ansible_facts.xorg | default({})} | to_nice_json }}'
        dest: /etc/ansible/facts.d/xorg.fact
        mode: "0644"

    - name: Write xrandr variable as local fact
      ansible.builtin.copy:
        content: '{{ {"xrandr": ansible_facts.xrandr | default({})} | to_nice_json }}'
        dest: /etc/ansible/facts.d/xrandr.fact
        mode: "0644"

    - name: Write drm variable as local fact
      ansible.builtin.copy:
        content: '{{ {"drm": ansible_facts.drm | default({})} | to_nice_json }}'
        dest: /etc/ansible/facts.d/drm.fact
        mode: "0644"

    - name: Write xorg_config variable as local fact
      ansible.builtin.copy:
        content: '{{ {"xorg_config": ansible_facts.XorgConfig | default({}) } | to_nice_json }}'
        dest: /etc/ansible/facts.d/xorg_config.fact
        mode: "0644"

- name: Update xorg, xrandr and drm variables with values from local facts if needed
  ansible.builtin.set_fact:
    xorg: "{{ ansible_local.xorg.xorg }}"
    xrandr: "{{ ansible_local.xrandr.xrandr }}"
    drm: "{{ ansible_local.drm.drm }}"
    xorg_config: "{{ ansible_local.xorg_config.xorg_config }}"
  when:
    - ansible_facts.xrandr is undefined
    - ansible_facts.xorg is undefined
    - ansible_facts.drm is undefined
    - ansible_facts.xorg_config is undefined

- name: Check if nvidia-smi is installed
  ansible.builtin.command: nvidia-smi
  register: nvidia_smi
  changed_when: false
  failed_when: false

- name: Set nvidia_driver_detected variable
  ansible.builtin.set_fact:
    nvidia_driver_installed: "{{ nvidia_smi.rc == 0 | bool | default(false) }}"

- name: Server flags config snippet to disable screen blanking
  ansible.builtin.template:
    src: templates/10-serverflags.conf.j2
    dest: /etc/X11/xorg.conf.d/10-serverflags.conf
    mode: "0644"
