- name: Create initramfs hook to copy EDID files
  ansible.builtin.template:
    src: templates/include-edid-data.sh.j2
    dest: '/etc/initramfs-tools/hooks/include-edid-data'
    mode: '0755'
    force: true

- name: "Create /lib/firmware/edid"
  ansible.builtin.file:
    state: directory
    dest: /lib/firmware/edid
    mode: '0755'

- name: Show kms_set_boot_edid variable
  ansible.builtin.debug:
    var: kms_set_boot_edid
    verbosity: 0

- name: Show display configuration
  ansible.builtin.debug:
    var: ansible_facts['display_config']
    verbosity: 0

- name: Show display configuration
  ansible.builtin.debug:
    var: ansible_facts['display_outputs'][ansible_facts['display_config']['primary']['connector']]
    verbosity: 0

- name: Boot options
  ansible.builtin.debug:
    msg: >-
      {% if ansible_facts['display_config']['primary'] | default(false) %}
      {% set primary = ansible_facts['display_config']['primary']['connector'] | default(false) %}
      {% set secondary = ansible_facts['display_config']['secondary']['connector'] | default(false) %}
      {% set primary_data = ansible_facts['display_outputs'][primary] %}
      video={{ primary_data['drm_name'] }}:ansible_facts['display_config']['primary']['resolution']}}@{{ansible_facts['display_config']['primary']['refreshrate']}}:eD {%
        if secondary
      %}{% set secondary_data = ansible_facts['display_outputs'][secondary] %},{{ secondary_data['drm_name'] }}:ansible_facts['display_config']['secondary']['resolution']}}@{{ansible_facts['display_config']['secondary']['refreshrate']}}:eD{% endif %}
      drm.edid_firmware={{ primary_data.drm_name }}:edid/{{ primary_data.xrandr_name }}.edid{%
        if secondary and secondary_data['drm_name'] is defined and secondary_data['edid'] is defined
      %},{{ secondary_data.drm_name }}:edid/{{ secondary_data.xrandr_name }}.edid{% endif %}
      {% endif %}


- name: "Set kms_boot_options variable"
  ansible.builtin.set_fact: # the formatting is important to get the correct spaces in the result
    kms_boot_options: >-
      {% if ansible_facts['display_config']['primary'] | default(false) %}
      {% set primary = ansible_facts['display_config']['primary']['connector'] | default(false) %}
      {% set secondary = ansible_facts['display_config']['secondary']['connector'] | default(false) %}
      {% set primary_data = ansible_facts['display_outputs'][primary] %}
      video={{ primary_data['drm_name'] }}:ansible_facts['display_config']['primary']['resolution']}}@{{ansible_facts['display_config']['primary']['refreshrate']}}:eD {%
        if secondary
      %}{% set secondary_data = ansible_facts['display_outputs'][secondary] %},{{ secondary_data['drm_name'] }}:ansible_facts['display_config']['secondary']['resolution']}}@{{ansible_facts['display_config']['secondary']['refreshrate']}}:eD{% endif %}
      drm.edid_firmware={{ primary_data.drm_name }}:edid/{{ primary_data.xrandr_name }}.edid{%
        if secondary and secondary_data['drm_name'] is defined and secondary_data['edid'] is defined
      %},{{ secondary_data.drm_name }}:edid/{{ secondary_data.xrandr_name }}.edid{% endif %}
      {% endif %}

  when: kms_set_boot_edid
  changed_when: true
  notify: ['Update Initramfs', 'Update GRUB']
