- name: Create initramfs hook to copy EDID files
  ansible.builtin.template:
    src: templates/include-edid-data.sh.j2
    dest: '/etc/initramfs-tools/hooks/include-edid-data'
    mode: '0755'
    force: true

- name: "Create /lib/firmware/edid"
  ansible.builtin.file:
    state: directory
    dest: /lib/firmware/edid
    mode: '0755'

- name: Show kms_set_boot_edid variable
  ansible.builtin.debug:
    var: kms_set_boot_edid
    verbosity: 0

- name: Show display configuration
  ansible.builtin.debug:
    var: ansible_facts['display_config']
    verbosity: 0

- name: Show display configuration
  ansible.builtin.debug:
    var: ansible_facts['display_outputs'][ansible_facts['display_config']['primary']['connector']]
    verbosity: 0

- name: Boot options
  ansible.builtin.debug:
    msg: >-
      {% if ansible_facts['display_config']['primary'] | default(false)
      %}{% set primary = ansible_facts['display_config']['primary']['connector'] | default(false)
      %}{% set primary_resolution = ansible_facts['display_config']['primary']['resolution'] | default(omit)
      %}{% set primary_refreshrate = ansible_facts['display_config']['primary']['refreshrate'] | default(60)
      %}{% set primary_data = ansible_facts['display_outputs'][primary]
      %}{% set primary_xrandr = primary_data['xrandr_name']
      %}{% set primary_drm = primary_data['drm_name']
      %}{% set secondary = ansible_facts['display_config']['secondary']['connector'] | default(false)
      %}{% if secondary
      %}{% set secondary_data = ansible_facts['display_outputs'][secondary]
      %}{% set secondary_resolution = ansible_facts['display_config']['secondary']['resolution'] | default(omit)
      %}{% set secondary_refreshrate = ansible_facts['display_config']['secondary']['refreshrate'] | default(60)
      %}{% set secondary_data = ansible_facts['display_outputs'][secondary]
      %}{% set secondary_xorg = secondary_data['xrandr_name']
      %}{% set secondary_drm = secondary_data['drm_name']
      %}{% endif %}
      video={{ primary_drm }}:{{ primary_resolution }}@{{ primary_refreshrate }}:eD{%
        if secondary
      %} video={{ secondary_drm }}:{{ secondary_resolution }}@{{ secondary_refreshrate }}:eD{% endif %}
      drm.edid_firmware={{ primary_drm }}:edid/edid.{{ primary_xrandr}}.bin{%
        if secondary and secondary_data['drm_name'] | bool and secondary_data['edid'] is definednd and secondary_data['edid'] | bool
      %},{{ secondary_data.drm_name }}:edid/edid.{{ secondary_data.xrandr_name }}.bin{% endif %}
      {% endif %}



- name: "Set kms_boot_options variable"
  ansible.builtin.set_fact: # the formatting is important to get the correct spaces in the result
    kms_boot_options: >-
      {% if ansible_facts['display_config']['primary'] | default(false)
      %}{% set primary = ansible_facts['display_config']['primary']['connector'] | default(false)
      %}{% set primary_resolution = ansible_facts['display_config']['primary']['resolution'] | default(omit)
      %}{% set primary_refreshrate = ansible_facts['display_config']['primary']['refreshrate'] | default(60)
      %}{% set primary_data = ansible_facts['display_outputs'][primary]
      %}{% set primary_xrandr = primary_data['xrandr_name']
      %}{% set primary_drm = primary_data['drm_name']
      %}{% set secondary = ansible_facts['display_config']['secondary']['connector'] | default(false)
      %}{% if secondary
      %}{% set secondary_data = ansible_facts['display_outputs'][secondary]
      %}{% set secondary_resolution = ansible_facts['display_config']['secondary']['resolution'] | default(omit)
      %}{% set secondary_refreshrate = ansible_facts['display_config']['secondary']['refreshrate'] | default(60)
      %}{% set secondary_data = ansible_facts['display_outputs'][secondary]
      %}{% set secondary_xorg = secondary_data['xrandr_name']
      %}{% set secondary_drm = secondary_data['drm_name']
      %}{% endif %}
      video={{ primary_drm }}:{{ primary_resolution }}@{{ primary_refreshrate }}:eD{%
        if secondary
      %} video={{ secondary_drm }}:{{ secondary_resolution }}@{{ secondary_refreshrate }}:eD{% endif %}
      drm.edid_firmware={{ primary_drm }}:edid/edid.{{ primary_xrandr}}.bin{%
        if secondary and secondary_data['drm_name'] | bool and secondary_data['edid'] is definednd and secondary_data['edid'] | bool
      %},{{ secondary_data.drm_name }}:edid/edid.{{ secondary_data.xrandr_name }}.bin{% endif %}
      {% endif %}


  when: kms_set_boot_edid
  changed_when: true
  notify: ['Update Initramfs', 'Update GRUB']
