- name: Create initramfs hook to copy EDID files
  ansible.builtin.template:
    src: templates/include-edid-data.sh.j2
    dest: '/etc/initramfs-tools/hooks/include-edid-data'
    mode: '0755'
    force: true

- name: "Create /lib/firmware/edid"
  ansible.builtin.file:
    state: directory
    dest: /lib/firmware/edid
    mode: '0755'

- name: Show kms_set_boot_edid variable
  ansible.builtin.debug:
    var: kms_set_boot_edid
    verbosity: 0

- name: "Set kms_boot_options variable"
  ansible.builtin.set_fact:
    kms_boot_options: >-
      video={{ drm.primary.drm_connector }}:D{%
        if drm.secondary is defined and drm.secondary.drm_connector is defined
      %},{{ drm.secondary.drm_connector }}:D{% endif %}
      drm.edid_firmware={{ drm.primary.drm_connector }}:edid/{{ drm.primary.edid }}{%
        if drm.secondary is defined and drm.secondary.drm_connector is defined and drm.secondary.edid is defined
      %},{{ drm.secondary.drm_connector }}:edid/{{ drm.secondary.edid }}{% endif %}
      {% for ignored_c in drm.ignored_outputs %} video={{ ignored_c }}:d{% endfor %}
  when: kms_set_boot_edid | bool
  notify: ['Update Initramfs', 'Update GRUB']
