---
# file: roles/yavdr-xorg/tasks/main.yml
- name: Import setup-xorg.yml
  ansible.builtin.import_tasks: setup-xorg.yml
  # tags: [install, update]

- name: Detect and apply Xorg configuration
  ansible.builtin.import_tasks: detect-xorg.yml
  # tags: [xorg.detect, install]

- name: Debug | show kms_set_boot_edid
  ansible.builtin.debug:
    var: kms_set_boot_edid
    verbosity: 0

- name: Get nouveau firmwares
  ansible.builtin.include_role:
    name: nouveau-firmware
  when: nvidia_detected and not nvidia_driver_installed

- name: Include write-display-config role
  ansible.builtin.include_role:
    name: write-display-config
  # tags: [xorg.detect, install]

- name: KMS Settings
  ansible.builtin.include_tasks: kms.yml
  tags: [xorg.detect, install]
  when: kms_set_boot_edid
