---
# file: roles/yavdr-xorg/tasks/main.yml
- name: Import setup-xorg.yml
  ansible.builtin.import_tasks: setup-xorg.yml
  tags: [install, update]

- name: Detect and apply Xorg configuration
  ansible.builtin.import_tasks: detect-xorg.yml
  tags: [xorg.detect, install]

- name: KMS Settings
  ansible.builtin.import_tasks: kms.yml
  tags: [xorg.detect, install]
  when: intel_detected | bool or (nvidia_detected | bool and not nvidia_driver_detected) or amd_detected
