---
# file: roles/yavdr-xorg/tasks/main.yml
- name: Import setup-xorg.yml
  ansible.builtin.import_tasks: setup-xorg.yml
  tags: [install, update]

- name: Detect and apply Xorg configuration
  ansible.builtin.import_tasks: detect-xorg.yml
  tags: [xorg.detect, install]

# TODO: what packages do we really need?
# - name: Install mesa vdpau drivers
#   ansible.builtin.apt:
#     name: mesa-va-drivers
#     state: present
#   when: ansible_facts.nvidia_detected and not nvidia_driver_installed or amd_detected

- name: Debug | show kms_set_boot_edid
  ansible.builtin.debug:
    var: kms_set_boot_edid
    verbosity: 0

- name: VDR-config | set nvidia video output method for softhddevice
  ansible.builtin.lineinfile:
    path: /etc/vdr/conf.avail/softhddevice.conf
    state: present
    regexp: "^-v .*"
    line: "-v {{ 'nvdec-egl' if nvidia_driver_installed else softhddevice_vaapi_output_method }}"
  when: (ansible_facts.nvidia_detected and nvidia_driver_installed)

- name: KMS Settings
  ansible.builtin.include_tasks: kms.yml
  tags: [xorg.detect, install]
  when: kms_set_boot_edid

- name: Include write-display-config role
  ansible.builtin.include_role:
    name: write-display-config
