---
# file: roles/yavdr-xorg/tasks/setup-xorg.yml

- name: Apt | remove obsolete packages for xorg
  ansible.builtin.apt:
    name:
      - xlogin
      - yavdr-xorg
    state: absent

- name: Create directories for systemd drop-in files
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "/etc/systemd/system/vdr.service.d/"
    - "/etc/systemd/system/user@{{ vdr.uid }}.service.d/"
    - "/etc/X11/xorg.conf.d/"
    - "{{ vdr.home }}/.config/systemd/user/"

- name: Create yavdr-xorg
  ansible.builtin.template:
    src: templates/systemd/system/yavdr-xorg.service.j2
    dest: "/lib/systemd/system/yavdr-xorg.service"
    mode: "0644"
  notify: ["Reload Units"]

# - name: Systemd-Drop-In | add dependency to X-server for vdr.service
#   ansible.builtin.template:
#     src: templates/vdr-xorg.conf
#     dest: /etc/systemd/system/vdr.service.d/vdr-xorg.conf
#     mode: "0644"
#   notify: ["Reload Units"]
- name: Remove existing /etc/systemd/system/vdr.service.d/vdr-xorg.conf
  ansible.builtin.file:
    path: /etc/systemd/system/vdr.service.d/vdr-xorg.conf
    state: absent

- name: Add a login shell for the user vdr
  ansible.builtin.user:
    name: "{{ vdr.user }}"
    shell: "/bin/bash"
    state: present
    uid: "{{ vdr.uid }}"
    groups: "{{ vdr.group }}"
    append: true

- name: Apt | install packages for xorg
  ansible.builtin.apt:
    name:
      - edid-decode
      - python3-dbus2vdr
      - python3-dotenv
      - python3-pydantic
      - python3-yavdr-frontend
      - tmux
      - feh
      - xdg-utils
      - openbox
      - read-edid
      - xserver-xorg-input-all
      - xserver-xorg-video-all
      - dbus-user-session
      - xorg
    state: present

- name: Apt | install intel xorg driver
  ansible.builtin.apt:
    name:
      - xserver-xorg-video-intel
    state: present
  when: intel_driver == 'intel'

- name: Set the vdr instance id for yavdr-frontend
  yaml_edit:
    path: /etc/yavdr-frontend/config.yml
    key: vdr.id
    int_value: "{{ vdr.instance_id | default(0) }}"

- name: YaVDR frontend | set attach on startup to "{{ yavdr_frontend.attach_on_startup }}"
  yaml_edit:
    path: /etc/yavdr-frontend/config.yml
    key: vdr.attach_on_startup
    str_value: "{{ yavdr_frontend.attach_on_startup }}"

- name: Set the detached background for yaVDR Frontend
  yaml_edit:
    path: /etc/yavdr-frontend/config.yml
    key: backgrounds.detached.path
    str_value: "{{ yavdr_frontend.backgrounds_detached_path | default('/usr/share/yavdr/images/yaVDR_background_detached.jpg') }}"

- name: Apt | install packages for Intel IGP
  ansible.builtin.apt:
    name:
      - i965-va-driver-shaders
      - intel-media-va-driver-non-free
      - libgl1-amber-dri
    state: present
  when: intel_detected | bool and not nvidia_detected | bool

- name: Apt | install packages for AMD GPUs
  ansible.builtin.apt:
    name:
      - mesa-va-drivers
    state: present
  when: amd_detected | bool and not nvidia_detected | bool

- name: Install yaVDR Media (e.g. Backgrounds)
  ansible.builtin.apt:
    name: yavdr-media

# - name: Command | write keyboard configuration to /etc/X11/xorg.conf.d/00-keyboard.conf
#   ansible.builtin.command: write-x11-keyboard-config
#   args:
#     creates: /etc/X11/xorg.conf.d/00-keyboard.conf
# NOTE: write-x11-keyboard-config is in the xlogin package
# Ubuntu's systemd is patched, so it does not create the file automatically

- name: Apt | install basic desktop programs
  ansible.builtin.apt:
    name:
      - xterm
      - kiosk-browser
    state: present
