---

- name: Install nfs server packages
  ansible.builtin.apt:
    name:
      - nfs-kernel-server
      - nfs-common
    state: present
    install_recommends: false

- name: Create /etc/exports
  ansible.builtin.template:
    src: templates/nfs-exports.j2
    dest: /etc/exports
    mode: '0644'
  notify: ['Restart NFS Kernel Server']

- name: Populate /etc/avahi/services
  ansible.builtin.template:
    src: templates/avahi/service.j2
    dest: '/etc/avahi/services/yavdr-{{ item.key }}.service'
    mode: '0644'
  loop: '{{ media_dirs | dict2items }}'
