---
# file: roles/yavdr-common/defaults/main.yml

branch: experimental
repositories:
  - 'ppa:yavdr/{{branch}}-main'
  - 'ppa:yavdr/{{branch}}-vdr'
  - 'ppa:yavdr/{{branch}}-kodi'
  - 'ppa:yavdr/{{branch}}-yavdr'

rpi_repositories:
  - 'ppa:yavdr/{{branch}}-main'
  - 'ppa:yavdr/{{branch}}-vdr'

timezone: 'Europe/Berlin'
default_locale: 'de_DE.UTF-8'
generate_locales:  # see entries in /etc/locale.gen
  - 'de_DE.UTF-8 UTF-8'
  - 'en_US.UTF-8 UTF-8'
language_packs:
  - language-pack-de
  - language-pack-en

drivers:
  sundtek: auto
  ddvb-dkms: auto

extra_packages:
  - vim
  - tree
  - w-scan

vdr:
    user: vdr
    group: vdr
    uid: 666
    gid: 666
    home: /var/lib/vdr
    recdir: /srv/vdr/video
    hide_first_recording_level: false
    safe_dirnames: true
    override_vdr_charset: ""
vdr_allowed_hosts: []

standby_reload_dvb: true
