---
# file roles/wakeup/defaults/main.yml

# Method can be 'acpiwakeup' or 'stm32wakeup'
wakeup_method: "acpiwakeup"
# How many minutes to start the VDR ahead?
wakeup_start_ahead: 5

# Days of the week for regular wake-ups (empty=Disabled, 1=Monday...7=Sunday)
wakeup_days: ""
# Time of each day for regular wake-ups (<24-hours>:<minutes>, e.g. "01:00")
wakeup_time: ""
