[project]
name = "helpers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible-runner>=2.4.2",
    "fastapi[standard]>=0.124.0",
    "jsonref>=1.1.0",
    "ruamel-yaml>=0.18.16",
]


[project.scripts]
ansible_test = "helpers.ansible_test:get_vars"

[tool.uv]
package = true
